# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
  config-server:
    image: egamorim/config-server:latest
    restart: always
    ports:
      - 8888:8888